# Generated by Django 3.2.3 on 2021-11-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20211117_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatboard',
            name='board_num',
            field=models.CharField(choices=[('1', '자유'), ('2', '건의'), ('3', '영화 추천'), ('4', '파티 모집')], default='1', max_length=50),
        ),
    ]
