# Generated by Django 3.2.3 on 2021-11-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_chatboard_board_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatboard',
            name='board_num',
            field=models.CharField(choices=[('1', '자유'), ('2', '건의'), ('3', '영화 추천'), ('4', '파티 모집')], max_length=50),
        ),
    ]
