# Generated by Django 3.2.3 on 2021-11-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_chatboard_board_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='board_num',
            field=models.CharField(default='5', max_length=10),
        ),
    ]
