# Generated by Django 3.2.3 on 2021-11-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_review_board_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='board_num',
        ),
    ]
