# Generated by Django 3.2.3 on 2021-11-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211118_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='video',
            new_name='video_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
